print ("Let's find the area of a trapezoid!")
base_a = input("Enter Base A in cm")
base_b = input("Enter Base B in cm")
height = input("Enter height in cm")
a_b = int(base_a) + int(base_b)
ab2 = int(a_b) / int(2)
final = int(ab2) * int(height)
print("Your final answer is!")
print(final)
